server:
  port: 8083

spring:
  application:
    name: greenmangaming-monitor
  mail:
    host: smtp.gmail.com
    port: 587
    username: paulloestevam@gmail.com
    password: aaaa aaaa aaaa aaaa # Senha de app
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

email:
  sender: "paulloestevam@gmail.com"

logging:
  file:
    name: logs/console.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB
      max-history: 7
  level:
    root: INFO
    com.paulloestevam.greenmangaming_monitor:

webdriver:
  chrome:
    # Deixe vazio no Linux se tiver instalado via apt.
    # No Windows, passe o caminho via argumento na execução.
    driver-path: ""

gmg:
  urls:
    - "https://www.greenmangaming.com/pt/hot-deals/"

scheduler:
  time: "0 0 9 * * *" # Executa todo dia às 10:00

# Filtros
minDiscountPercentage: 90
productLineWidth: 300